name: animal_repository
description: Dart package which manages the animal domain.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.0
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.2
  intl: ^0.19.0
  shelter_repository:
    path: ../shelter_repository
  type_repository:
    path: ../type_repository
  quality_repository:
    path: ../quality_repository